# Site settings
title: Music
#header-img: img/home-bg.jpg
email: luiarthur@ucsc.edu
copyright_name: Arthur Lui
description: "Notes on Harmony and Counterpoint"
baseurl: ""
url: "http://luiarthur.github.io"

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title # pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]

collections:
  notes:
    output: true
    permalink: /notes/:path/

